version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbit-0
    ports:
      - 5673:5673
      - 5672:5672
      - 15672:15672
    networks:
      - default

  # tensorflow:
  #   image: tensorflow_app
  #   hostname: tensorflow-0
  #   restart: unless-stopped
  #   networks:
  #     - default

  app_a-0:
    image: app_a
    hostname: app_a-0
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      - default

networks:
  default:
    external:
      name: net1