version: "1.0"
services:
  rabbitmq:
    image: rabbitmq:management
    hostname: my-rabbit
    ports:
      - 5673:5673
      - 5672:5672
      - 15672:15672
    networks:
      - default

  app_a:
    image: app_a
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      - default

networks:
  default:
    external:
      name: net1